[project]
name = "applic"
version = "0.1.0"
description = "УЗИ протоколирование (перенос UI на PySide6)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "PySide6>=6.8.0",
  "python-docx>=1.1.2",
  "pyinstaller>=6.10.0",
]

[tool.uv]
package = false

